### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/gnome-sdk#101]
When running `drawing`, I'm getting 
`/snap/drawing/27/gnome-platform/command-chain/desktop-launch: /snap/drawing/27/usr/bin/drawing: /snap/gnome-42-2204-sdk/current/usr/bin/python3: bad interpreter: No such file or directory`

Same is for one of my apps, which I'm packing for snap. What can be done for this?

**Comment by Wazzaps** [comment]
I'm getting this with my own snap, what was the solution?

**Comment by soumyaDghosh** [comment]
The python interpreter path, in the main binary file needs to be set as /usr/bin/python3

Like here I'm doing
https://github.com/soumyaDghosh/dialect-snap/blob/main/snap/snapcraft.yaml#L48

**Comment by Wazzaps** [comment]
Yep I ended up doing something similar. What a pain!
You would think packaging a gnome app would be simple under snap, without hacks :/
Thanks anyway :)

**Comment by soumyaDghosh** [comment]
Gnome+python has some issues
