### ISSUE TITLE
webkit2gtk-5 almost ready but don't know how to test

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/gnome-sdk#125]
I have a snap that uses webkit3gtk-5. So, I build the webkit2gtk-5 from source there. I got only two error regarding references from icu73 and zlib1g. If we build these two from source with latest tags in `gnome-sdk`, we can push `webkit2gtk-5` in this snap. But, I am unable to test any of them, because `snapcraft remote-build` can't clone the folders, the patches fail to work, github ci auto pauses itself. So, I have no choice. Should I create a PR with the `icu73` first then push others to make the ground for `webkit2gtk-5`?

**Comment by ghost** [comment]
@soumyaDghosh  I need to build webkit6 for wike, can i get the source for your build i can use it as a reference ?

**Comment by soumyaDghosh** [comment]
It can't be built within a snap, conflicts with libicu files.
