### ISSUE TITLE
Please patch Intel 13th gen support into iHD_drv_video.so

### ISSUE THREAD

**Issue by vanvugt** [ubuntu/gnome-sdk#133]
Please patch Intel 13th gen support into `iHD_drv_video.so`. Like we did in https://launchpad.net/bugs/2004237

Or more simply, update intel-media-driver to >= 22.4.2

**Comment by vanvugt** [comment]
Ideally in future this should move into the mesa graphics driver snap so we only need to do hardware enablement once.

**Comment by sergio-costas** [comment]
Can you check the test snap?

**Comment by vanvugt** [comment]
> Can you check the test snap?

I can see the source code in cad2a6e3b0865e8837a683ed0609e0b217c95117 but where is the "test snap"?

**Comment by sergio-costas** [comment]
> > Can you check the test snap?
> 
> I can see the source code in [cad2a6e](https://github.com/ubuntu/gnome-sdk/commit/cad2a6e3b0865e8837a683ed0609e0b217c95117) but where is the "test snap"?

Oh, sorry... I put the link in Jira... I think that I pointed you...

**Comment by vanvugt** [comment]
I can only see https://github.com/ubuntu/gnome-sdk/pull/134

**Comment by vanvugt** [comment]
Landed in cad2a6e3b0865e8837a683ed0609e0b217c95117
