### ISSUE TITLE
Gnome SDK lacks pipewire libraries

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/gnome-sdk#163]
Currently there is no pipewire library in gnome sdk. Also need 3 environment variables which are needed to be auto added. Should I try to add pipewire in the gnome-sdk?

**Comment by iomezk** [comment]
<s>Pipewire audio playback should be available since snapd-2.61 which is in latest/beta now.</s>

**Comment by soumyaDghosh** [comment]
Not playback, but the libraries which are often needed by apps for screensharing/camera etc

**Comment by iomezk** [comment]
> Not playback, but the libraries which are often needed by apps for screensharing/camera etc

I doubt it could work before the snapd-2.61 for snaps with `confinement: strict`

**Comment by soumyaDghosh** [comment]
Yes they work. Just look into the chromium or the webcord snap
