### ISSUE TITLE
Bundling the complete gstreamer in gnome-sdk

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/gnome-sdk#177]
The `gnome-sdk` for snap currently ships only gstreamer libraries which are needed by other libraries as dependency. But, we can simply bundle all the gstreamer libraries in the gnome-sdk? This would eliminate the duplication of these libraries too.

**Comment by kenvandine** [comment]
So you are suggesting we bundle the gstreamer dev packages in the sdk snap?  Do you have a list of those packages you would like to see?  I think we would need to also update the desktop-launch script to set the appropriate variables necessary to find gstreamer components in the content snap, which would simplify things.

**Comment by soumyaDghosh** [comment]
We can add all the sets of gstreamer libraries in the `sdk` as well as `content` snap. Which includes. `base`, `good`, `bad` and `ugly`. Also, ffmpeg related gstreamer libraries like `gst-libav` can be included but, it needs to have ffmpeg installed. Which will again clash with a lot of sdk files.
