### ISSUE TITLE
Extension deletes user personal files from Music, Templates, Public, Desktop

### ISSUE THREAD

**Issue by popey** [ubuntu/gnome-sdk#188]
The gnome extension deleted all my ~/Music ~/Public ~/Templates ~/Desktop.

I was prototyping a snap which tries to store files in `$SNAP_USER_DATA/Appname`, but the user expects the files to be `$HOME/Appname`. So I set an environment variable in the `apps` section of `snapcraft.yaml`.

## Steps to reproduce

Backup your ~/Music, ~/Public, ~/Templates and ~/Desktop folders

Build a snap which has the following:

```yaml
apps:
  environment:
    HOME: $SNAP_REAL_HOME
```

Install and run the snap.

Your ~/Music folder will be replaced with a recursive symlink to itself, deleting all the previous contents. 

## Expected outcome

The gnome extension should:

a) Do better checks before arbitrarily replacing files in the $HOME folder
b) Not delete user files

**Comment by soumyaDghosh** [comment]
https://forum.snapcraft.io/t/snap-real-home-is-kinda-buggy/34463

similar issue, I posted in the forum sometimes ago

**Comment by kenvandine** [comment]
@sergio-costas @jhenstridge any thoughts on how to deal with this?

**Comment by sergio-costas** [comment]
I'll check the scripts in gnome extension...

**Comment by sergio-costas** [comment]
@kenvandine I think that this patch should fix it... https://github.com/snapcore/snapcraft-desktop-integration/pull/25

**Comment by sergio-costas** [comment]
I'll try to test it in a VM...

**Comment by kenvandine** [comment]
> @kenvandine I think that this patch should fix it... [snapcore/snapcraft-desktop-integration#25](https://github.com/snapcore/snapcraft-desktop-integration/pull/25)

I think that would fix it.  My initial reaction to this approach was that it would not create the necessary bookmarks, but actually in this use case we don't need to create those at all.

**Comment by sergio-costas** [comment]
Tested, and it works.

**Comment by kenvandine** [comment]
This fix is in the candidate channel of gnome-42-2204 now

**Comment by popey** [comment]
(I'm not convinced this should be "closed" until it's in stable, but that's your decision. :innocent: 

I tested this via the following method:

* Installed Kubuntu 22.04 in a VM
* Confirm home directories are intact

![image](https://github.com/ubuntu/gnome-sdk/assets/1841272/6f6a6c2a-8a5d-492e-88ee-72066fd9217c)

* `snap refresh gnome-42-2204 --candidate`
* `snap install dosbox-staging`
* `snap run dosbox-staging`
* Confirm home directories are still intact
* `snap remove --purge dosbox-staging`
* `rm -rf ~/snap/dosbox-staging`
* `snap refresh gnome-42-2204 --stable`
* `snap install dosbox-staging`
* `snap run dosbox-staging`
* Confirm home folders become symlinks to themselves.

![image](https://github.com/ubuntu/gnome-sdk/assets/1841272/d1beffbd-0639-4bfc-870a-4cf72d62cffd)

I believe this confirms the issue is fixed in the candidate channel, and certainly still broken in the stable channel.

**Comment by Recydywa** [comment]
Not sure, if it adds anything, seeing the issue is closed, but I can also confirm that running dosbox-staging in combination with gnome-42-2204 from candidate channel resolves the problem.
