### ISSUE TITLE
Missing armhf builds for gnome-46-2404{,-sdk}

### ISSUE THREAD

**Issue by past-due** [ubuntu/gnome-sdk#215]
Similar to #87

I've been looking to rebase our snap on core24 and gnome-46-2404.

One of the requirements is that it needs to be built for amd64, arm64 and armhf, just as we currently do with core22 and gnome-42-2204.

Armhf architecture seems to be missing for gnome-46-2404 builds, thus blocking the upgrade.

**Comment by past-due** [comment]
@kenvandine would it be possible to either get some clarification on which architectures are going to be supported going forwards, or (ideally) to publish this one for armhf as well? Thanks in advance.

**Comment by nteodosio** [comment]
This is an issue for Chromium and, [I must assume](https://launchpad.net/~mozilla-snaps/firefox/+snap/firefox-snap-stable), Firefox too.

**Comment by seb128** [comment]
Is anyone still use armhf on the desktop? We haven't been producing Ubuntu desktop images for it for years and our snap metrics show pretty low number of users...
