### ISSUE TITLE
Gnome 46 2404 - xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb

### ISSUE THREAD

**Issue by JGCarroll** [ubuntu/gnome-sdk#232]
Users have started reporting
```
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
```

And the snaps do not load at all.

E.G.,
https://github.com/JGCarroll/pinta-snap/issues/12
https://forum.snapcraft.io/t/snap-run-xkbcommon-error-failed-to-add-default-include-path-usr-share-x11-xkb/41041/4

I'm assuming this is on a phased rollout as I cannot reproduce locally.

**Comment by be1** [comment]
I think gnome-sdk is missing `xkb-data` stuff:
https://forum.snapcraft.io/t/snap-run-xkbcommon-error-failed-to-add-default-include-path-usr-share-x11-xkb/41041/6?u=be1

**Comment by sameersharma2006** [comment]
I Reported it at wrong place.
https://github.com/canonical/mesa-2404/issues/3#issuecomment-2176014858

**Comment by nteodosio** [comment]
Broke Chromium on core24 too: https://launchpad.net/bugs/2073339.

Reverting Gnome-46-2404 to revision 26 works:

```
% printf %s\\n /snap/gnome-*/current/usr/share/X11/xkb
/snap/gnome-3-38-2004/current/usr/share/X11/xkb
/snap/gnome-42-2204/current/usr/share/X11/xkb
% snap revert ...
% snap info ...
channels:
  latest/stable:    0+git.18eace2 2024-07-15 (39) 422MB -
  latest/candidate: 0+git.18eace2 2024-07-09 (39) 422MB -
  latest/beta:      ↑
  latest/edge:      0+git.18eace2 2024-07-09 (39) 422MB -
installed:          0+git.b6706a3            (26) 511MB -
% printf %s\\n /snap/gnome-*/current/usr/share/X11/xkb
/snap/gnome-3-38-2004/current/usr/share/X11/xkb
/snap/gnome-42-2204/current/usr/share/X11/xkb
/snap/gnome-46-2404/current/usr/share/X11/xkb
```

**Comment by seb128** [comment]
The xkb-data package has been added back to the staged packages now
