### ISSUE TITLE
New candidate revision (r57) breaks gnome-clock

### ISSUE THREAD

**Issue by seb128** [ubuntu/gnome-sdk#256]
according to https://github.com/ubuntu/desktop-snaps/issues/804 

> /usr/lib/x86_64-linux-gnu/libgeocode-glib.so.0 was removed which seems like a shared library

was that expected? it is at least breaking the gnome-clocks candidate snap

```
$ /snap/bin/gnome-clocks 
/snap/gnome-clocks/477/usr/bin/gnome-clocks: error while loading shared libraries: libgeocode-glib.so.0: cannot open shared object file: No such file or directory
```

**Comment by sergio-costas** [comment]
Mmm... I think that libgeocode, when compiled with `libsoup-2.4`, is named `libgeocode-glib`, while when compiled with `libsoup-3.0` is named `libgeocode-glib-2`. Also, according to the meson build file from gnome-clocks (https://github.com/GNOME/gnome-clocks/blob/46954c339415cdf514b68d79a19ee8d78378c7a4/meson.build#L17), at build time it checks whether libgweather was built with libsoup-2.4 or libsoup-3.0, and decides which one to use based on that. So rebuilding gnome-clock would be enough.

But I will check if it's possible to have both libgweather libraries...

**Comment by seb128** [comment]
Thanks for checking. We didn't declare the new sdk stable yet so I think it's fine that it changing this way now, no need to build a second variant. I'm closing that bug and we will rebuild gnome-clocks
