### ISSUE TITLE
 New candidate revision (r57) breaks gnome-recipes

### ISSUE THREAD

**Issue by seb128** [ubuntu/gnome-sdk#258]
Using the new rev 57 build

```
$ /snap/bin/gnome-recipes 
/snap/gnome-recipes/44/usr/bin/gnome-recipes: error while loading shared libraries: libsoup-2.4.so.1: cannot open shared object file: No such file or directory
```

is gnome-recipes a special case or is there something else in the stack still needing libsoup2.4 which we didn't include when deciding to remove that version?

**Comment by sergio-costas** [comment]
Clearly, gnome-recipes require libsoup-2.4, which was removed in the last gnome-46 snap. We can either create a new revision of gnome-recipes with libsoup-2.4 embedded, or we can restore libsoup-2.4 in gnome-46 (although keeping the other libraries depending on libsoup-3.0).

**Comment by seb128** [comment]
We discussed that topic before removing libsoup from the sdk and agreed that any remaining users of the old version could either stick to core22 or build libsoup as a part so we just need to fix gnome-recipes. The main purpose of the report against the sdk was to make sure we checked that gnome-recipe was in that case and that we didn't break anything transient depends in the sdk which would impact applications.

I'm closing that report according to that and will open one against gnome-recipe

**Comment by sergio-costas** [comment]
Perfect. Anyway, I have to fix another bug that prevents building gnome-recipes (https://github.com/ubuntu/gnome-sdk/issues/260). As soon as I test it, I'll upload the PR.
