### ISSUE TITLE
Poppler missing from gnome-42 SDK and runtime

### ISSUE THREAD

**Issue by lucyllewy** [ubuntu/gnome-sdk#57]
While working towards porting GIMP development release (2.99 with a view to turning into GIMP 3.0 when upstream are ready) to core22 I have stumbled on an issue where poppler is missing from the `gnome-42-2204` and `gnome-42-2204-sdk` snaps. Installing the deb packages from the Ubuntu 22.04 repository brings with them dependencies on conflicting versions of libraries that poppler and other gnome libraries depend upon, such as libharfbuzz. When attempting to link against poppler from the Ubuntu repo ld reports missing harfbuzz-related symbols due to the conflicting versions of libharfbuzz. I suspect there are numerous other knock on effects.

Resolution: compile and install poppler in the gnome-42 platform and sdk snaps.

**Comment by sergio-costas** [comment]
Fixed.
