### ISSUE TITLE
librsvg is 106MB

### ISSUE THREAD

**Issue by mardy** [ubuntu/gnome-sdk#70]
I just noticed this:

```
mardy@boxxo:~$ ls -l /snap/gnome-3-38-2004/112/usr/lib/librsvg-2.so.2.47.0
-rwxr-xr-x 1 root root 106687008 мая 18 17:24 /snap/gnome-3-38-2004/112/usr/lib/librsvg-2.so.2.47.0
```

(same size in revision 106). Something is wrong here, since the same version of the library installed as a deb on focal is less than 10MB (still bigger than necessary, at least according to http://forum.tinycorelinux.net/index.php?topic=24799.0).

**Comment by kenvandine** [comment]
This is fixed in the candidate channel, will get promoted to stable soon.
