### ISSUE TITLE
Update libadwaita to 1.2

### ISSUE THREAD

**Issue by jbicha** [ubuntu/gnome-sdk#73]
GNOME 43.0 is being released this week. Nearly every core GNOME app has switched to the new About dialog provided by libadwaita 1.2.

Instead of including a libadwaita part in all of our GNOME snaps, could we just update the version of libadwaita we provide in the gnome42 content snap to 1.2? It looks like it's buildable with Jammy's GTK4 4.6.

I think that's the only library update we need for the GNOME stuff we snap for GNOME 43.

Like usual, Epiphany will need a new webkitgtk but that should be coming via jammy-security before too long.

**Comment by jbicha** [comment]
(gnome-text-editor wants updated glib, gtk4, and gtksourceview5.)

**Comment by 3v1n0** [comment]
Also, please sync the patch with the new one in ubuntu (https://salsa.debian.org/gnome-team/libadwaita/-/blob/ubuntu/master/debian/patches/ubuntu/style-manager-Support-Yaru-accent-colors.patch) that should be ideally backported too (if we've other gnome sdk's including it already).

**Comment by kenvandine** [comment]
> Also, please sync the patch with the new one in ubuntu (https://salsa.debian.org/gnome-team/libadwaita/-/blob/ubuntu/master/debian/patches/ubuntu/style-manager-Support-Yaru-accent-colors.patch) that should be ideally backported too (if we've other gnome sdk's including it already).

I've refreshed the patch for gnome-42-2204-sdk, but we're still getting an unlreated build failure in libgweather that i haven't had time to look at.

**Comment by sergio-costas** [comment]
Libadwaita is already at 1.2.0... is the patch also updated and this can be closed, or the patch is still pending?

**Comment by sergio-costas** [comment]
Ok, it is updated, so I'll close this.
