### ISSUE TITLE
Missing armhf builds for gnome-42-2204{,-sdk}

### ISSUE THREAD

**Issue by oSoMoN** [ubuntu/gnome-sdk#87]
I've been experimenting with rebasing the firefox snap on core22 and gnome-42-2204.
One of the requirements is that it needs to be built for amd64, arm64 and armhf. That last architecture is missing for gnome-42-2204 builds, thus is blocking the upgrade for firefox.

**Comment by bandali** [comment]
Can this be closed now @kenvandine?

**Comment by kenvandine** [comment]
armhf builds are now published, thanks!
