### ISSUE TITLE
gnome-42-2204 uses relatively new kernel features

### ISSUE THREAD

**Issue by merlijn-sebrechts** [ubuntu/gnome-sdk#90]
After switching signal-desktop to core22 gnome extension, the snap started to crash on Centos.

https://github.com/snapcrafters/signal-desktop/issues/76

This seems to be caused by the snap using the `clone3()` syscall, which is not supported by the kernel of Centos.

Is it possible to compile gnome-42-2204 with support for older kernels?

**Comment by kenvandine** [comment]
That doesn't sound like it's from the content snap but from core22 itself.  I would expect glibc?

**Comment by merlijn-sebrechts** [comment]
Ok, makes sense. Where should I report issues with core22 itself?

**Comment by merlijn-sebrechts** [comment]
Found it!

https://github.com/snapcore/core-base/issues/92
