### ISSUE TITLE
Add WebP support

### ISSUE THREAD

**Issue by ma8ma** [ubuntu/gnome-sdk#95]
Hi, folks.

I would like to show webp images on Snap GTK applications.
If I understand correctly, GNOME SDK needs libwebp library and [webp-pixbuf-loader][a] to support webp. Is there anything I can do to help get the library and loader into the SDK?

[a]: https://github.com/aruiz/webp-pixbuf-loader

**Comment by cameronwhite** [comment]
I think this should be fixed by #96 ?

**Comment by kenvandine** [comment]
> I think this should be fixed by #96 ?

Yes, which has landed in the gnome-42-2204-sdk snap.  Next I need to get it into gnome-42-2204 and do some testing before we land it in stable

**Comment by kenvandine** [comment]
This is now available in gnome-42-2204 in candidate and should make it to stable once we make it through testing.

**Comment by ma8ma** [comment]
@kenvandine 
Thank you for update! It works fine for my app.
